#' Example Dataset for chi_fisher
#'
#' A small synthetic dataset included with *AssumpSure* for demonstrating 
#' Fisher & Chi-square tests in the Fisher & Chi-square tab.
#'
#' The file is stored in `inst/extdata/chi_fisher.csv`.
#'
#' All values are synthetic, created only for demonstration; no human data were used,
#' and no ethical approval or consent is required.
#'
#' @format A CSV file with 101 rows and 2 columns:
#' \describe{
#'   \item{sex}{Sex.}
#'   \item{location}{Location.}
#' }
#'
#' @source Simulated data generated by the author.
#'
#' @examples
#' read.csv(system.file("extdata", "chi_fisher.csv", package = "AssumpSure"))
#' @name chi_fisher
NULL
