#' Example Dataset for plantgrowth
#'
#' A small synthetic dataset included with *AssumpSure* for demonstrating 
#' one-way ANOVA in the Continuous Data Tests tab.
#'
#' The file is stored in `inst/extdata/plantgrowth.csv`.
#'
#' All values are synthetic, created only for demonstration; no human data were used,
#' and no ethical approval or consent is required.
#'
#' @format A CSV file with 31 rows and 2 columns:
#' \describe{
#'   \item{weight}{Plant weight.}
#'   \item{group}{Treatment group.}
#' }
#'
#' @source Simulated data generated by the author.
#'
#' @examples
#' read.csv(system.file("extdata", "plantgrowth.csv", package = "AssumpSure"))
#' @name plantgrowth
NULL
